### ISSUE TITLE
ISSUE-1.1- Santiago - ISSUE SELECTION - Adding the Travelling Salesman Problem TheAlgorithms#5564

### ISSUE THREAD

**Issue by ba-00001** [CIS3590-G1B/GROUP-1B-Java#1]
### What would you like to Propose?

. @santycarbahol complete this part 

### Issue details

.@santycarbahol complete this part 

### Additional Information

.@santycarbahol complete this part

**Comment by ba-00001** [comment]
@santycarbahol Complete the issue description and update the Issue name - > Issue 1 - "name of the task you are working on"

**Comment by santycarbahol** [comment]
What would you like to Propose?
[FEATURE REQUEST] Adding the Travelling Salesman Problem #5564

Issue details
Problem Statement: Given a set of cities and the distances between each pair, the objective is to find the shortest possible route that visits each city exactly once and returns to the starting point.

Additional Information
No more additional infromarmation

**Comment by santycarbahol** [comment]
Adding the Travelling Salesman Problem 

What would you like to Propose?
For this project, I'd like to create a tree or an algorithm that can determine the short path, such as BFS or DFS, which would compare the distance between cities and choose the shortest route. 

Issue details
Problem Statement: Given a set of cities and the distances between each pair, the objective is to find the shortest possible route that visits each city exactly once and returns to the starting point.

Additional Information
No more additional information

[FEATURE REQUEST] Adding the Travelling Salesman Problem https://github.com/TheAlgorithms/Java/issues/5564
