### ISSUE TITLE
ISSUE#1.2.1- SANTIAGO - ISSUE DEVELOPMENT - README DOCUMENTATION

### ISSUE THREAD

**Issue by ba-00001** [CIS3590-G1B/GROUP-1B-Java#19]
# Weekly Build Documentation Template - Issues [Insert Issue Numbers]

## Repository: [Insert Repository Name with Link]

---

### **Objective:**
Document the progress for the following issues:
- **Issue #X.X:** [Insert Issue Title (e.g., Feature Development)]
- **Issue #X.X:** [Insert Issue Title (e.g., Testing and Validation)]
- **Issue #X.X:** [Insert Issue Title (e.g., Pull Request Preparation)]

---

#### **Week [Insert Week Number] Tasks:**
- [ ] Define the core components of the feature or functionality.
- [ ] Implement the feature in the relevant language or framework.
- [ ] Ensure that input/output specifications are correctly handled.

#### **Progress Summary:**
- **Feature Development:** 
  - The initial design is complete, and the basic implementation has been written.
  - Code is modularized to enhance readability and maintainability.

#### **Challenges Encountered:**
- Handling edge cases required additional consideration, such as invalid input or specific data structure constraints.

#### **Key Commit:**
- `feat: implemented core functionality for [Insert Feature Name]`

#### **Next Steps:**
- Focus on refining edge cases and improving error handling or optimization.

---

#### **Week [Insert Week Number] Tasks:**
- [ ] Develop comprehensive test cases (typical, boundary, and edge cases).
- [ ] Use appropriate testing tools (e.g., JUnit, PyTest, etc.).
- [ ] Debug the implementation using test-driven development.

#### **Progress Summary:**
- **Test Case Development:**
  - Basic tests for typical cases have been written.
  - Boundary cases (e.g., small input, large input, etc.) are also covered.

#### **Challenges Encountered:**
- Handling edge cases that cause the system or algorithm to fail unexpectedly, such as invalid inputs.

#### **Key Commit:**
- `test: added basic and edge case tests for [Insert Feature/Functionality Name]`

#### **Next Steps:**
- Conduct performance and stress testing to ensure the feature handles large datasets or complex input efficiently.

---

#### **Week [Insert Week Number] Tasks:**
- [ ] Prepare the code for submission in a pull request.
- [ ] Ensure the repository follows coding guidelines and best practices.
- [ ] Create documentation for reviewers and link related issues.

#### **Progress Summary:**
- **Pull Request:**
  - The pull request draft is ready, with all changes documented and code commented for clarity.
  - Linked all relevant issues for proper tracking.

#### **Challenges Encountered:**
- Ensuring all tests pass before submission and integrating feedback from code reviews.

#### **Key Commit:**
- `chore: prepared pull request and linked relevant issues`

#### **Next Steps:**
- Finalize the pull request submission and ensure that the feature passes all required tests.

---

## **Commit Guidelines for This Week:**

Each commit will adhere to the following format for consistency:
- **Commit Message Format:**
  - `feat: [description of feature]`
  - `fix: [description of bug fix]`
  - `test: [description of test]`
  - `refactor: [description of refactoring task]`

### Example Commit Messages for this Week:
- `feat: implemented core functionality for [Insert Feature]`
- `fix: handled edge cases for [Insert Feature]`
- `test: added test cases for [Insert Feature]`

---

## **Next Steps and Upcoming Tasks:**
- Continue refining the feature based on peer feedback.
- Finalize testing and documentation for the final pull request.
- Conduct performance testing and review for optimizations.

---

## **Version Control Summary:**

This section summarizes all commits made during the week to ensure proper tracking of changes.

| **Date**       | **Changes Made**                            | **Commit ID** |
|----------------|---------------------------------------------|---------------|
| [Insert Date]  | Implemented basic feature functionality      | [Commit ID]   |
| [Insert Date]  | Added test cases for typical and edge cases  | [Commit ID]   |
| [Insert Date]  | Refactored code and prepared pull request    | [Commit ID]   |

---

## **Documentation Guidelines and References:**
For more information on how to structure the repository, make effective commit messages, and ensure security, refer to:
- [How to Write READMEs for Repositories](https://guides.github.com/features/wikis/)
- [How to Write Effective Commit Messages](https://chris.beams.io/posts/git-commit/)
- [How to Secure Repositories](https://docs.github.com/en/github/administering-a-repository/securing-your-repository)

**Comment by santycarbahol** [comment]
Weekly Build Documentation Template - Issues #5564
Repository: binary-tree-dfs-bfs
Week [Insert Week Number] - Documentation for Issues #5564
 
Objective:
Document the progress for the following issue:

Issue #5564: Adding the Travelling Salesman Problem (BFS Algorithm in Java)

Week  Tasks:
Describe the essential elements of the capability or feature. #30 Could you put Traveling's BFS algorithm into practice?
.Salesman Problem in Java
Ensure that input/output specifications are correctly handled.
Progress Summary:
Feature Development:

The initial design for the Travelling Salesman Problem (TSP) using Java's Best-First Search (BFS) algorithm is complete.
The basic implementation is functional with a modular approach for readability and maintainability.
The distance matrix input handling for multiple cities is implemented, ensuring scalability.
Challenges Encountered:
We are handling cities with a large number of permutations that require optimization for performance.
Edge cases like circular paths and cities with zero distances added complexity in ensuring the correctness

Issue #5564: Testing and Validation

Week [Insert Week Number] Tasks:
Develop comprehensive test cases (typical, boundary, and edge cases) for the BFS algorithm.
Use JUnit to validate the Java implementation.
Debug the BFS implementation using test-driven development.
Progress Summary:
Test Case Development:

Basic tests for typical cases are written.
Boundary cases for small and large city inputs are covered.
Tests for circular paths and cities with equal distances are designed.
Challenges Encountered:
Ensuring correct BFS behavior when multiple cities have similar paths or costs.
Handling large city inputs where performance becomes critical.
Key Commit:
test: added basic and edge case tests for Travelling Salesman Problem using BFS

Next Steps:
Conduct performance testing to ensure the BFS algorithm handles large datasets efficiently.
Integrate additional test cases to validate edge scenarios (e.g., cities with zero distances).

Issue #5564: Pull Request Preparation

Week [Insert Week Number] Tasks:
Prepare the BFS implementation for submission in a pull request.
Ensure the repository follows Java coding guidelines and best practices.
Create documentation for reviewers and link related issues.
Progress Summary:
Pull Request:

The pull request draft is ready, with comments and clear documentation on the BFS approach for the Travelling Salesman Problem.
All relevant issues, including performance and testing, are linked for proper tracking.
Challenges Encountered:
Ensuring all JUnit tests pass before submission.
Handling feedback from code reviews, especially regarding optimization.
Key Commit:
chore: prepared to pull requests and linked relevant issues for Travelling Salesman Problem

Next Steps:
Finalize pull request submission after performance and testing are confirmed.
Ensure the feature passes all required tests before merging.


Memory updated
Here’s how you can fill in the Weekly Build Documentation Template for issue Adding the Travelling Salesman Problem #5564 using the BFS algorithm in Java:

Weekly Build Documentation Template - Issues #5564
Repository: [Insert Repository Name with Link]
Week [Insert Week Number] - Documentation for Issues #5564

Objective:
Document the progress for the following issue:

Issue #5564: Adding the Travelling Salesman Problem (BFS Algorithm in Java)

Week [Insert Week Number] Tasks:
Define the core components of the feature or functionality. #30
Implement the BFS algorithm for the Travelling Salesman Problem in Java.
Ensure that input/output specifications are correctly handled.
Progress Summary:
Feature Development:

The initial design for the Travelling Salesman Problem (TSP) using Java's Best-First Search (BFS) algorithm is complete.
The basic implementation is functional with a modular approach for readability and maintainability.
The distance matrix input handling for multiple cities is implemented, ensuring scalability.
Challenges Encountered:
We are handling cities with a large number of permutations that require optimization for performance.
Edge cases like circular paths and cities with zero distances added complexity in ensuring correctness.
Key Commit:
feat: implemented core functionality for Travelling Salesman Problem using BFS algorithm

Next Steps:
Focus on refining edge cases, particularly cities with multiple paths of equal distance.
Optimize performance for larger inputs and ensure scalability of the BFS approach.
Issue #5564: Testing and Validation

Week [Insert Week Number] Tasks:
Develop comprehensive test cases (typical, boundary, and edge cases) for the BFS algorithm.
Use JUnit to validate the Java implementation.
Debug the BFS implementation using test-driven development.
Progress Summary:
Test Case Development:

Basic tests for typical cases are written.
Boundary cases for small and large city inputs are covered.
Tests for circular paths and cities with equal distances are designed.
Challenges Encountered:
Ensuring correct BFS behavior when multiple cities have similar paths or costs.
Handling large city inputs where performance becomes critical.
Key Commit:
test: added basic and edge case tests for Travelling Salesman Problem using BFS

Next Steps:
Conduct performance testing to ensure the BFS algorithm handles large datasets efficiently.
Integrate additional test cases to validate edge scenarios (e.g., cities with zero distances).
Issue #5564: Pull Request Preparation

Week [Insert Week Number] Tasks:
Prepare the BFS implementation for submission in a pull request.
Ensure the repository follows Java coding guidelines and best practices.
Create documentation for reviewers and link related issues.
Progress Summary:
Pull Request:

The pull request draft is ready, with comments and clear documentation on the BFS approach for the Travelling Salesman Problem.
All relevant issues, including performance and testing, are linked for proper tracking.
Challenges Encountered:
Ensuring all JUnit tests pass before submission.
Handling feedback from code reviews, especially regarding optimization.
Key Commit:
chore: prepared to pull requests and linked relevant issues for Travelling Salesman Problem

Next Steps:
Finalize pull request submission after performance and testing are confirmed.
Ensure the feature passes all required tests before merging.
Commit Guidelines for This Week:
Each commit will adhere to the following format for consistency:

Commit Message Format:

feat: [description of feature]
fix: [description of bug fix]
test: [description of test]
refactor: [description of refactoring task]
Example Commit Messages for this Week:
feat: implemented core functionality for Travelling Salesman Problem using BFS
fix: handled edge cases for BFS implementation
test: added test cases for the Travelling Salesman Problem in the BFS algorithm
Next Steps and Upcoming Tasks:
Continue refining the BFS feature based on peer feedback.
Finalize performance testing and documentation.
Conduct stress testing for large datasets to ensure scalability.


.
