### ISSUE TITLE
ISSUE#1.3.1- SANTIAGO - ISSUE TESTING - README DOCUMENTATION

### ISSUE THREAD

**Issue by ba-00001** [CIS3590-G1B/GROUP-1B-Java#24]
### What would you like to share?

# Weekly Build Documentation Template - Issues [Insert Issue Numbers]

## Repository: [Insert Repository Name with Link]

---

### **Objective:**
Document the progress for the following issues:
- **Issue #X.X:** [Insert Issue Title (e.g., Feature Development)]
- **Issue #X.X:** [Insert Issue Title (e.g., Testing and Validation)]
- **Issue #X.X:** [Insert Issue Title (e.g., Pull Request Preparation)]

---

#### **Week [Insert Week Number] Tasks:**
- [ ] Define the core components of the feature or functionality.
- [ ] Implement the feature in the relevant language or framework.
- [ ] Ensure that input/output specifications are correctly handled.

#### **Progress Summary:**
- **Feature Development:** 
  - The initial design is complete, and the basic implementation has been written.
  - Code is modularized to enhance readability and maintainability.

#### **Challenges Encountered:**
- Handling edge cases required additional consideration, such as invalid input or specific data structure constraints.

#### **Key Commit:**
- `feat: implemented core functionality for [Insert Feature Name]`

#### **Next Steps:**
- Focus on refining edge cases and improving error handling or optimization.

---

#### **Week [Insert Week Number] Tasks:**
- [ ] Develop comprehensive test cases (typical, boundary, and edge cases).
- [ ] Use appropriate testing tools (e.g., JUnit, PyTest, etc.).
- [ ] Debug the implementation using test-driven development.

#### **Progress Summary:**
- **Test Case Development:**
  - Basic tests for typical cases have been written.
  - Boundary cases (e.g., small input, large input, etc.) are also covered.

#### **Challenges Encountered:**
- Handling edge cases that cause the system or algorithm to fail unexpectedly, such as invalid inputs.

#### **Key Commit:**
- `test: added basic and edge case tests for [Insert Feature/Functionality Name]`

#### **Next Steps:**
- Conduct performance and stress testing to ensure the feature handles large datasets or complex input efficiently.

---

#### **Week [Insert Week Number] Tasks:**
- [ ] Prepare the code for submission in a pull request.
- [ ] Ensure the repository follows coding guidelines and best practices.
- [ ] Create documentation for reviewers and link related issues.

#### **Progress Summary:**
- **Pull Request:**
  - The pull request draft is ready, with all changes documented and code commented for clarity.
  - Linked all relevant issues for proper tracking.

#### **Challenges Encountered:**
- Ensuring all tests pass before submission and integrating feedback from code reviews.

#### **Key Commit:**
- `chore: prepared pull request and linked relevant issues`

#### **Next Steps:**
- Finalize the pull request submission and ensure that the feature passes all required tests.

---

## **Commit Guidelines for This Week:**

Each commit will adhere to the following format for consistency:
- **Commit Message Format:**
  - `feat: [description of feature]`
  - `fix: [description of bug fix]`
  - `test: [description of test]`
  - `refactor: [description of refactoring task]`

### Example Commit Messages for this Week:
- `feat: implemented core functionality for [Insert Feature]`
- `fix: handled edge cases for [Insert Feature]`
- `test: added test cases for [Insert Feature]`

---

## **Next Steps and Upcoming Tasks:**
- Continue refining the feature based on peer feedback.
- Finalize testing and documentation for the final pull request.
- Conduct performance testing and review for optimizations.

---

## **Version Control Summary:**

This section summarizes all commits made during the week to ensure proper tracking of changes.

| **Date**       | **Changes Made**                            | **Commit ID** |
|----------------|---------------------------------------------|---------------|
| [Insert Date]  | Implemented basic feature functionality      | [Commit ID]   |
| [Insert Date]  | Added test cases for typical and edge cases  | [Commit ID]   |
| [Insert Date]  | Refactored code and prepared pull request    | [Commit ID]   |

---

## **Documentation Guidelines and References:**
For more information on how to structure the repository, make effective commit messages, and ensure security, refer to:
- [How to Write READMEs for Repositories](https://guides.github.com/features/wikis/)
- [How to Write Effective Commit Messages](https://chris.beams.io/posts/git-commit/)
- [How to Secure Repositories](https://docs.github.com/en/github/administering-a-repository/securing-your-repository)

**Comment by santycarbahol** [comment]
Weekly Build Documentation Template - Issues TheAlgorithms#5564
Repository: https://github.com/TheAlgorithms/Java/issues/5564

Week 5 - Documentation for Issue TheAlgorithms#5564

Objective:
Document the progress for the following issue:

Issue TheAlgorithms#5564: Adding the Travelling Salesman Problem (BFS Algorithm in Java)
Feature Development

Week 5 Tasks:

Could you describe the essential elements of the Travelling Salesman Problem (TSP) solution?
Implement the BFS algorithm in Java to solve the TSP.
Ensure that input/output specifications for the BFS solution are correctly handled.
Progress Summary:

Initial Design: Completed for TSP using Java's Best-First Search (BFS) algorithm.
Implementation: Basic functionality is working with a modular approach, enhancing readability and maintainability.
Input Handling: Designed to accommodate a distance matrix for multiple cities, ensuring scalability for various input sizes.
Challenges Encountered:

Permutation Handling: Addressed the complexity of handling a large number of city permutations, requiring optimization.
Edge Cases: Incorporated handling for circular paths and cities with zero distances, adding complexity in validating solution correctness.
Key Commit:

feat: implemented core functionality for Travelling Salesman Problem using BFS algorithm
Next Steps:

Refine the handling of cities with multiple paths of equal distances.
Optimize performance for larger inputs, ensuring scalability.
Testing and Validation
Week 5 Tasks:

Develop comprehensive test cases, covering typical, boundary, and edge cases.
Use JUnit to validate the Java BFS implementation.
Debug the BFS solution using a test-driven development approach.
Progress Summary:

Test Cases: Developed for typical cases; boundary cases for small and large city inputs.
Additional Tests: Designed for circular paths and cities with equal distances.
Challenges Encountered:

Behavior Validation: Ensuring correct BFS behavior when multiple cities have similar paths or costs.
Large Inputs: Managing performance for large datasets where optimization becomes critical.
Key Commit:

test: added basic and edge case tests for Travelling Salesman Problem using BFS
Next Steps:

Conduct performance testing to confirm that the BFS algorithm efficiently handles large datasets.
Add more test cases to validate edge scenarios, such as cities with zero distances.
Pull Request Preparation
Week 5 Tasks:

Prepare the BFS implementation for submission in a pull request.
Ensure compliance with Java coding guidelines and best practices in the repository.
Create documentation for reviewers, linking related issues for context.
Progress Summary:

Pull Request: The draft is ready, with detailed comments and documentation on the BFS approach for TSP.
Issue Linking: Linked all relevant issues to maintain tracking of performance and testing aspects.
Challenges Encountered:

JUnit Compliance: Ensuring all JUnit tests pass before submission.
Code Review Feedback: Addressing review feedback, especially regarding optimization improvements.
Key Commit:

chore: prepared to pull requests and linked relevant issues for Travelling Salesman Problem
Next Steps:

Please go ahead and finalize the pull request submission after confirming the successful performance and test results.
Ensure the feature passes all required tests before merging into the main branch.
Commit Guidelines for This Week:
Each commit will adhere to the following format for consistency:

Commit Message Format:

feat: for new features
fix: for bug fixes
test: for test cases
refactor: for refactoring tasks
Example Commit Messages:

feat: implemented core functionality for Travelling Salesman Problem using BFS
fix: handled edge cases for BFS implementation
test: added test cases for the Travelling Salesman Problem in the BFS algorithm
Next Steps and Upcoming Tasks:
Refine the BFS solution based on peer feedback.
Complete performance testing and finalize documentation.
Conduct stress testing to ensure scalability for large datasets.
