### ISSUE TITLE
ISSUE#2.1 - LEO - ISSUE SELECTION - Add Moore's Voting Algorithm

### ISSUE THREAD

**Issue by ba-00001** [CIS3590-G1B/GROUP-1B-Java#3]
### What would you like to Propose?

@LEO UPDATE THIS WITH ISSUE YOU WILL BE WORKING ON

### Issue details

@LEO UPDATE THIS WITH ISSUE YOU WILL BE WORKING ON

### Additional Information

@LEO UPDATE THIS WITH ISSUE YOU WILL BE WORKING ON

**Comment by leochirinos10** [comment]
What would you like to Propose?

My proposal is to implement an algorithm that finds the majority element in an array, where the majority element is defined as the element that appears more than half of the time.

Issue details

The algorithm uses a candidate and a counter. The algorithm selects a candidate and it counts its occurrences using the counter. It verifies if the candidate is actually the one with the most occurrences.

Additional Information

No more additional information

[FEATURE REQUEST] Add Moore's Voting Algorithm [TheAlgorithms#5636](https://github.com/TheAlgorithms/Java/issues/5636)
