### ISSUE TITLE
ISSUE#3.2- RANI - ISSUE DEVELOPMENT

### ISSUE THREAD

**Issue by ba-00001** [CIS3590-G1B/GROUP-1B-Java#7]
`  
# Algorithm Development Template  
**ISSUE#: [Issue Number]**  
**Title: [Issue Title]**  
**Prepared by: [Developer Name]**  
**Date: [MM/DD/YYYY]**

---

## 1. Problem Definition and Clarification
   - **Objective**: Clearly state the problem that the algorithm needs to solve.  
   - **Key Questions**:
     - What is the problem to be solved?
     - What are the expected outcomes?
   - **Sub-tasks**: Break down the issue into smaller tasks.

---

## 2. Input/Output Specifications
   - **Input Data**:
     - Define the required input data types, format, and constraints.
   - **Expected Output**:
     - Specify what the algorithm should return or produce after execution.

---

## 3. Constraints and Requirements
   - **Time Complexity**: What is the acceptable time complexity for the solution?
   - **Space Complexity**: Define memory usage constraints.
   - **Resource Constraints**:
     - CPU, memory, and other hardware limitations.
   - **Ethical Considerations** (if applicable):
     - How will the algorithm ensure fairness, privacy, or comply with legal requirements?

---

## 4. Data Structures
   - **Chosen Data Structures**: List the data structures (arrays, trees, hash maps, etc.) that are ideal for solving the problem and why.
   - **Justification**: Explain why these data structures will improve efficiency.

---

## 5. Algorithm Design Approach
   - **Design Paradigm**:
     - Choose one or more design paradigms (e.g., Greedy, Divide and Conquer, Dynamic Programming, etc.).
     - Explain why the paradigm is suitable for this problem.
   - **Modular Design**:
     - Break down the algorithm into reusable functions or components for clarity and maintainability.

---

## 6. Edge Cases and Error Handling
   - **Edge Cases**:
     - Identify possible edge cases (e.g., null values, empty inputs, extreme data).
   - **Error Handling**:
     - Include strategies to handle invalid input or unexpected behavior.

---

## 7. Optimization
   - **Initial Version**: Describe the basic working version of the algorithm.
   - **Optimization Techniques**: List any steps taken to optimize the algorithm for better performance (e.g., memoization, pruning, parallelization).

---

## 8. Testing and Debugging
   - **Test Cases**:
     - Typical input cases.
     - Boundary cases.
     - Edge cases.
   - **Debugging Tools**: Specify the tools or strategies used for debugging.

---

## 9. Documentation and Maintenance
   - **Documentation**:
     - Provide clear explanations of the algorithm, its functions, and how to use it.
   - **Maintenance Plan**:
     - Outline plans for future updates, bug fixes, and ongoing improvements.

---

### Comments/Notes  
[Additional notes or comments regarding the issue development.]

---

### Version History  
| Date       | Changes Made                        | Version |
|------------|-------------------------------------|---------|
| MM/DD/YYYY | Initial Draft                       | 1.0     |
| MM/DD/YYYY | [Describe subsequent changes]       | X.X     |

---

`

**Comment by RanyM-999** [comment]
I would like to propose the addition of the Shuffling Algorithm (such as Fisher-Yates) to the repository. This algorithm would be useful for providing a randomized order of the elements in a given list, ensuring randomness. Implementing this in Java would prove to be a useful addition to the existing repository.

The proposed implementation will be using the Fisher-Yates Algorithm in order to shuffle finite sequences and order elements by picking them from a list one by one until there are none left, therefore creating unbiased permutations where each possible combination is as likely as another.

[FEATURE REQUEST]: Add Shuffling Algorithm https://github.com/TheAlgorithms/Java/issues/5635

**Comment by RanyM-999** [comment]
`  
# Algorithm Development Document 1.0
**ISSUE#: 5635**  
**Title: Shuffling Algorithm**  
**Prepared by: Rany Moussa**  
**Date: 10/22/2024**

---

## 1. Problem Definition and Clarification
   - **Objective**: This algorithm aims to implement an algorithm that shuffles and randomizes the order of elements in a given list  
   - **Key Questions**:
     - What is the problem to be solved?
  The problem to be solved is ensuring all possible permutations of a list is equally likely at any given time.
     - What are the expected outcomes?
   The expected outcome is a unique list every time the algorithm is run
   - **Sub-tasks**: Break down the issue into smaller tasks.
          - Create a list of a certain size
          - Initialize a Random Generator
          - Iterate through list
          - Pick random index
          - Swap Elements
          - Repeat until completion

---

## 2. Input/Output Specifications
   - **Input Data**:
     - The input data could be integers or strings given in a list
   - **Expected Output**:
     - A fully randomized list of the given elements

---

## 3. Constraints and Requirements
   - **Time Complexity**: O(n)
   - **Space Complexity**: O(1)
   - **Resource Constraints**:
     - Performance on Larger Array lists
     - Quality of randomness
     - Memory Limitations
   - **Ethical Considerations** (if applicable):
     - N/A
---

## 4. Data Structures
   - **Chosen Data Structures**: Arrays and Lists
   - **Justification**: This method only works for those data structure types

---

## 5. Algorithm Design Approach
   - **Design Paradigm**:
     - Greedy
     - This algorithm is iterative, making localized decisions at each step and once a swap is made, it is never reversed
   - **Modular Design**:
     - 

---

## 6. Edge Cases and Error Handling
   - **Edge Cases**:
     - Empty Array or List
     - Single Element Array or List
     - Repeated Elements
     - Large Lists or Arrays
     - Non-Integer Elements
   - **Error Handling**:
     - The algorithm should return an empty or unchanged array in the first two cases, respectively, it should treat each repeated element as individual in the third case, and should be able to run normally in the last two cases.

---

## 7. Optimization
   - **Initial Version**: An algorithm that randomizes all elements of a list and returns said list.
   - **Optimization Techniques**: List any steps taken to optimize the algorithm for better performance (e.g., memoization, pruning, parallelization).

---

## 8. Testing and Debugging
   - **Test Cases**:
     - Typical input cases.
     - Boundary cases.
     - Edge cases.
   - **Debugging Tools**: Specify the tools or strategies used for debugging.

---

## 9. Documentation and Maintenance
   - **Documentation**:
     - Provide clear explanations of the algorithm, its functions, and how to use it.
   - **Maintenance Plan**:
     - Outline plans for future updates, bug fixes, and ongoing improvements.

---

### Comments/Notes  
[Additional notes or comments regarding the issue development.]

---

### Version History  
| Date       | Changes Made                        | Version |
|------------|-------------------------------------|---------|
| 10/22/2024 | Initial Draft                       | 1.0     |
| MM/DD/YYYY | [Describe subsequent changes]       | X.X     |

---


`
